apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
  namespace: kafka
spec:
  type: ClusterIP
  ports:
    - port: 2181
  selector:
    app: zookeeper

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: plaintext
    - port: 9999
      name: jmx
  clusterIP: None
  selector:
    app: kafka

---
kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: kafka-manager
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
